language: python
python:
- '3.5'
- '3.6'

install:
- python -m pip install -r requirements.txt
- python -m pip install pytest-cov coveralls

script:
- python -m pytest pipelines/ --cov=./ -v

after_success:
- coveralls

jobs:
  include:


    - stage: Deploy to PyPI
      env:
        secure: "Cv1FJ+tUYBGh/0sahip8TlvIEjXmW/BpZuXjTGTzXobT6CvAvYmoNkqz1aolu2r+X1ZhyXiUX9SCCkZ/JzCY5C203XPEgwUqKQ5JPWi/d/lxueUosWaYHDHw5VJJLUDQh49cOyHO/avodsgAwo6N8wr2aHNP+PdFs9V/K7OZkYxgYy/QSI/riQychJ9It7pvWUmLN0mClME4DNthXH30Y6mkvNHyQfESrZ15arz4YqlfZoNXrn2gQN8ZHg5XcDP1ERRG3om5KV8tnnKEZQsT3Of8F+qiw/ZlpOs1aaXDJm7TZOH20MqtAEJ6I7/ngd4Z/SUGeLcVI/tDwQL5EglAxD0THaGdmEw0sMOTKAYrc/QnD3bfZRl7gOagFoq0fvpJAIVhkd0+rEwYX8YjLRgxeaCSSq4MRJyFIhwQIXn8HNqoarssfqqRc3MtuFL5juhfySrwufhlsuWrV/Eh42PiPBTh6vwp/rz1mhrf7dtl4B7jX6JPGQp1ec/WlUyVnQXJHsyRyo9u8z4yl6RWm2YraHBkJINh1jF7szfdA3CG+agDQllSoOMRxpdKB0spw+KwT0GvRikoGaxMcyBpcjQQtr9kTeicV+JsbtVGNk796MDMpCXscupnfmSMwLz7WkXfUEft04GGUMIJu++SrOXImqqMlGR0fc+YgQHHianVUgM="
      language: python
      python: 3.6
      script:
        - git remote rm origin
        - git remote add origin https://${GITHUB_TOKEN}@github.com/rorymurdock/Lightning-Talk-Pipelines-2.git >/dev/null 2>&1
        - git checkout origin/master
        # - git push --set-upstream origin master
        - python3 increment_version.py
        - git status
        - git add -u
        - git status
        - git commit -m "[ci skip] version changed"
        - git status
        - git push --set-upstream origin master
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: rorymurdock
        password:
          secure: "MXPpgLOyA73NUKY+ci0xb5n1Y0nqWLQcyHWH4/u9CRk6na56LHbiLb+4oCPYDlGX5ti3sju4Ugp+R/HmATlLfoFCDolHk/iCSiC3XijHVxmZM3h0YAESYGWZQGHIjw9VNlPRxm82pX/fkuXVADwYAxlIAakrN+gAnzm/MPP4/k9dSom1QP/yMnS8dDjaLgVOLa/Dn5kYRhV1/Bv+fFkwUq/SJ+0JZOXGzYSD5Lkwn9z3XthWksP/bSZ84yEH0pvWsfLjXpW89s49K1PCdCcWDwW09KujHPQq1DKkhOBcriLSG1/oCLeyahmbJvDXduRyJXUBU5chHGcbfBcqXDMw0EfUqEe11aT1IHEVS48icC5tyQOcAmzNGOuhibFvybSSBtCYSjoEotbajp/aFYt2074IkhT38HHQp0aXD3ZyLO6zovF0XKu1R+UsVm3V+AYKyMMs7dFPsHeNt4S0Wy9Z6loHg2lSM4FjkaSlh9pJKl7JYDvExPTRpymQy64S0NDFQZ6ZBRqzdInZ+CUfUSNnBf8kitUx60q2i9monbzUoz92GU44ixtRbkFD47glwC3Wjzt9CRcZ1aK9lsOm8FOJrOqyDANNxLwuPVuWPuNUyHksw/pVgoutG4LbRM51cAq5hr50m5sf657h0/8ZXtxPClRZCIrfKTKhrYANAUU167E="
        on:
          branch: master
  