language: python
python:
  - "3.5"
  - "3.6"
  
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - python -m pip install pytest-cov coveralls

# command to run tests
script:
  - python -m pytest pipelines/ --cov=./ -v

after_success:
  - coveralls

# # Deploy to pypi
# deploy:
#   provider: pypi
#   user: $pypi_user
#   password: $pypi_password
#   on:
#     branch: master