language: python
python:
- '3.5'
- '3.6'
install:
- python -m pip install -r requirements.txt
- python -m pip install pytest-cov coveralls
script:
- python -m pytest pipelines/ --cov=./ -v
after_success:
- coveralls

# Deploy to pypi
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: rorymurdock
  password:
    secure: "MXPpgLOyA73NUKY+ci0xb5n1Y0nqWLQcyHWH4/u9CRk6na56LHbiLb+4oCPYDlGX5ti3sju4Ugp+R/HmATlLfoFCDolHk/iCSiC3XijHVxmZM3h0YAESYGWZQGHIjw9VNlPRxm82pX/fkuXVADwYAxlIAakrN+gAnzm/MPP4/k9dSom1QP/yMnS8dDjaLgVOLa/Dn5kYRhV1/Bv+fFkwUq/SJ+0JZOXGzYSD5Lkwn9z3XthWksP/bSZ84yEH0pvWsfLjXpW89s49K1PCdCcWDwW09KujHPQq1DKkhOBcriLSG1/oCLeyahmbJvDXduRyJXUBU5chHGcbfBcqXDMw0EfUqEe11aT1IHEVS48icC5tyQOcAmzNGOuhibFvybSSBtCYSjoEotbajp/aFYt2074IkhT38HHQp0aXD3ZyLO6zovF0XKu1R+UsVm3V+AYKyMMs7dFPsHeNt4S0Wy9Z6loHg2lSM4FjkaSlh9pJKl7JYDvExPTRpymQy64S0NDFQZ6ZBRqzdInZ+CUfUSNnBf8kitUx60q2i9monbzUoz92GU44ixtRbkFD47glwC3Wjzt9CRcZ1aK9lsOm8FOJrOqyDANNxLwuPVuWPuNUyHksw/pVgoutG4LbRM51cAq5hr50m5sf657h0/8ZXtxPClRZCIrfKTKhrYANAUU167E="
  on:
    branch: master